-- Seed de recursos de escritura. Punto de vista como destacado por defecto.
-- UUIDs fijos para que el seed sea idempotente (on conflict do update).

insert into public.recursos (id, titulo, descripcion, ejemplo_label, ejemplo_texto, destacado, orden) values
('a0000001-0001-4000-8000-000000000001', 'Punto de vista', 'Escribí sobre un secreto que sólo el aire conoce... ¿Qué historias transporta la brisa de la tarde?', 'EJEMPLO', '''Escribí sobre un secreto que sólo el aire conoce... ¿Qué historias transporta la brisa de la tarde?''', true, 0),
('a0000002-0001-4000-8000-000000000002', 'Diálogo', 'El diálogo es un artificio. No se trata únicamente de copiar lo que decimos. Debemos hacer un esfuerzo para encontrar la voz del personaje y que suene auténtica. Es importante que los diálogos por sí solos no expliquen o resuelvan la historia: la narración en su conjunto debe proveer los elementos para que eso ocurra. No es necesario que los personajes hablen directamente del conflicto. De hecho, si los conocemos bien, sabremos que en muchos casos, lo evitarían.', null, null, false, 1),
('a0000003-0001-4000-8000-000000000003', 'Escena', 'La escena es una unidad narrativa autónoma que pone a los personajes en acción: presenciamos los acontecimientos como si sucedieran frente a nosotros. Un cuento suele tener varias escenas.', null, null, false, 2),
('a0000004-0001-4000-8000-000000000004', 'Haiku', 'El haiku es un tipo de poesía japonesa, estructurada en un verso corto, un verso largo, un verso corto (generalmente de 5, 7 y 5 sílabas), que representa un instante o un sentimiento auténtico, sin necesidad de metáforas. En sus orígenes, estaba vinculado a la Naturaleza y la transmisión de una imagen, pero en Occidente esto se transformó y hay diversas interpretaciones al respecto, que incluyen poemas urbanos e incluso una versión llamada Haikumbia.', null, null, false, 3),
('a0000005-0001-4000-8000-000000000005', 'Manifiesto', 'Un manifiesto es un escrito que un movimiento político, religioso, filosófico o artístico dirige a la opinión pública para exponer y defender su programa de acción, que suele proponer un cuestionamiento y una modificación novedosa del statu quo.', null, null, false, 4),
('a0000006-0001-4000-8000-000000000006', 'Monólogo interior', 'El monólogo interior es la expresión de los sentimientos y pensamientos más profundos de un personaje sin que nada los medie, ni siquiera una organización lógica. Es el fluir de la conciencia, como si se pudiera traducir directamente lo que se piensa al papel, sea esto algo trivial o importante. El personaje no se detiene a encadenar los pensamientos, y de ese modo se revelan fragmentos del inconsciente. Los precursores de esta técnica son James Joyce y Virginia Woolf, autores atravesados por la influencia del psicoanálisis.', null, null, false, 5),
('a0000007-0001-4000-8000-000000000007', 'Narrador', 'El narrador cuenta la historia; el punto de vista es el ángulo desde el que se para. Cada tipo de narrador dispone de distinta información. Algunos narradores posibles son los que cuentan la historia en primera persona: el narrador protagonista y el narrador testigo. Todo lo que ocurra será mediado por su mirada, por eso es fundamental prestar atención a la voz. La diferencia entre ambos es que uno narra sus propias acciones y el otro, las historias de otros personajes. El narrador en tercera persona no es un personaje y solemos encontrarlo de las siguientes formas: Narrador omnisciente: lo sabe todo, qué pasó y por qué, cómo empieza y termina la historia, y lo que piensan los personajes, aun cuando ellos no lo saben. Focalizado o tercera al hombro: el narrador cuenta lo que sucede desde la subjetividad de un personaje, pero sin ser una primera persona. A veces, usa el estilo indirecto libre, que superpone ambas voces. Cámara: cuenta solo lo que se ve y lo que se escucha. No expresa nada del pasado ni del futuro, tampoco lo que sienten o piensan los personajes.', null, null, false, 6),
('a0000008-0001-4000-8000-000000000008', 'Oxímoron', 'El oxímoron es una figura retórica que consiste en usar dos conceptos de significado opuesto en una misma expresión, de modo que se genere un tercer concepto contradictorio pero posible. Por ejemplo: trabajadores desocupados, ruido silencioso, luz cegadora, realidad virtual.', null, null, false, 7),
('a0000009-0001-4000-8000-000000000009', 'Personaje', 'El personaje es la parte fundamental de la historia. Lo que cuento importa porque le importa al personaje. El personaje no es el autor, aun si lleva su nombre. Nunca debe ser juzgado, sino más bien comprendido. Me interesa conocer todos los matices, las ambigüedades, no estereotipar en lo bueno o en lo malo. Hay que trabajar en profundidad y singularizar, sin que eso signifique necesariamente exagerar las características. Se trata de dar pinceladas. Apuntar al detalle, mostrar en la acción cómo hace y dice cosas, y no explicar. Además, tenemos que conocer su interioridad, saber qué piensa y cómo se siente frente a las situaciones, aunque muchas veces eso se traduzca apenas en un gesto. El personaje siempre tiene motivaciones y es importante que le ocurra alguna modificación a lo largo del relato, no importa si es grande o pequeña.', null, null, false, 8),
('a000000a-0001-4000-8000-00000000000a', 'Presente histórico', 'El presente histórico es el uso del tiempo presente para contar hechos pasados. Hay que tener cuidado de no confundirlo con el presente real: el lector debe comprender que los hechos ya ocurrieron pero que el narrador está forzando la conjugación verbal. Esta temporalidad sirve para generar una sensación de inmediatez, como si estuviéramos en ese momento, a pesar de que no lo estamos.', null, null, false, 9),
('a000000b-0001-4000-8000-00000000000b', 'Registro', 'El registro es el tipo de lenguaje que emplean el narrador y los personajes: formal, coloquial, vulgar, etc.', null, null, false, 10),
('a000000c-0001-4000-8000-00000000000c', 'Tono', 'El tono es la emoción principal que se refleja en el estilo narrativo: humorístico, solemne, confesional, etc.', null, null, false, 11),
('a000000d-0001-4000-8000-00000000000d', 'Verosimilitud', 'La verosimilitud es la cualidad de lo que es verosímil; es lo que parece verdadero o lo que es creíble. Lo que se propone en la escritura tiene que ser coherente con las reglas que establece el texto, más allá de la realidad. El texto es una unidad que se sostiene a sí misma: cada narración tiene su lógica y la verosimilitud debe construirse en base a ella.', null, null, false, 12)
on conflict (id) do update set
  titulo = excluded.titulo,
  descripcion = excluded.descripcion,
  ejemplo_label = excluded.ejemplo_label,
  ejemplo_texto = excluded.ejemplo_texto,
  destacado = excluded.destacado,
  orden = excluded.orden,
  updated_at = now();
